default: &default
  adapter: postgresql
  username: postgres
  host: db
  port: 5432
  role: postgres

test:
  <<: *default
  database: code_corps_test
development:
  <<: *default
  database: code_corps_dev
